services:
  db:
    container_name: practica-db
    image: mysql:9.3
    volumes:
      - ./db_mysql:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mi_tienda
        MYSQL_USER: user
        MYSQL_PASSWORD: password